"""delete table REfreshToken

Revision ID: 406e215db4c2
Revises: 70531d465967
Create Date: 2025-11-14 10:02:09.333164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '406e215db4c2'
down_revision: Union[str, Sequence[str], None] = '70531d465967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_RefreshTokens_token'), table_name='RefreshTokens')
    op.drop_table('RefreshTokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RefreshTokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('RefreshTokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('RefreshTokens_pkey'))
    )
    op.create_index(op.f('ix_RefreshTokens_token'), 'RefreshTokens', ['token'], unique=False)
    # ### end Alembic commands ###
