"""update Estimate model

Revision ID: 5ee9a94c4615
Revises: 2d67bbe78b64
Create Date: 2025-12-06 10:40:39.685680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee9a94c4615'
down_revision: Union[str, Sequence[str], None] = '2d67bbe78b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Estimates', sa.Column('description', sa.String(length=255), server_default='', nullable=False))
    op.add_column('Estimates', sa.Column('project', sa.String(length=100), server_default='', nullable=False))
    op.add_column('Estimates', sa.Column('based_on', sa.String(length=100), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Estimates', 'based_on')
    op.drop_column('Estimates', 'project')
    op.drop_column('Estimates', 'description')
    # ### end Alembic commands ###
