"""rename table Users

Revision ID: 658718e8e6eb
Revises: 7ddbc12af1af
Create Date: 2025-11-13 09:52:11.362527

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '658718e8e6eb'
down_revision: Union[str, Sequence[str], None] = '7ddbc12af1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('User', 'Users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('Users', 'User')
    # ### end Alembic commands ###
