"""add index to Info.created-at

Revision ID: 81958e46153c
Revises: a108d7bebe20
Create Date: 2025-10-28 20:12:06.965413

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "81958e46153c"
down_revision: str | Sequence[str] | None = "a108d7bebe20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_Info_created_at"), "Info", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Info_created_at"), table_name="Info")
    # ### end Alembic commands ###
