"""change table name

Revision ID: a108d7bebe20
Revises: 1bbc7a20b898
Create Date: 2025-10-28 15:38:07.616665

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a108d7bebe20"
down_revision: str | Sequence[str] | None = "1bbc7a20b898"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("About", "Info")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("Info", "About")
    # ### end Alembic commands ###
